/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.kamiazya.graphviz

import kotlin.random.Random

open class Library {
    open fun someLibraryMethod(): Boolean = Random.nextBoolean()
}
